export const STORAGE_KEYS = {
  PRE_CONTEXT_TOKEN: "MENTRIXOS_PRE_CONTEXT_TOKEN",
  ACCESS_TOKEN: "MENTRIXOS_ACCESS_TOKEN",
  USER: "MENTRIXOS_USER",
  INSTITUTES: "MENTRIXOS_INSTITUTES",
  SELECTED_INSTITUTE: "MENTRIXOS_SELECTED_INSTITUTE",
  SELECTED_ROLE: "MENTRIXOS_SELECTED_ROLE",
};